-- AlterTable
ALTER TABLE "app_settings" ADD COLUMN     "labelBarcode" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "labelCols" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "labelFields" TEXT[] DEFAULT ARRAY['assetTag', 'model', 'company']::TEXT[],
ADD COLUMN     "labelGutterXMm" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
ADD COLUMN     "labelGutterYMm" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "labelMarginLeftMm" DOUBLE PRECISION NOT NULL DEFAULT 7,
ADD COLUMN     "labelMarginTopMm" DOUBLE PRECISION NOT NULL DEFAULT 12,
ADD COLUMN     "labelPageSize" TEXT NOT NULL DEFAULT 'A4',
ADD COLUMN     "labelQr" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "labelRows" INTEGER NOT NULL DEFAULT 8;

